/**IMAGES NOT OPTIMIZED**/
const menu = [
  {
    id: 1,
    title: 'Ribs with garlic sauce',
    category: 'Lunch',
    price: 15.99,
    img: 'https://images.unsplash.com/photo-1624234763734-c9629a2777c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
    desc: `Brooklyn pickled truffaut bushwick poutine flannel kinfolk man braid artisan. Banh mi heirloom viral truffaut ugh meh. Fashion axe meditation gluten-free ugh keffiyeh tattooed. PBR&B 3 wolf moon waistcoat asymmetrical jianbing. Portland pop-up chambray vape pickled blog fixie, fam prism woke kinfolk slow-carb palo santo pinterest gluten-free. Locavore neutra health goth, chillwave cray everyday carry portland chambray tilde. Single-origin coffee shabby chic etsy PBR&B.`,
  },
  {
    id: 2,
    title: 'Steak au poivre ',
    category: 'Lunch',
    price: 13.99,
    img: 'https://images.unsplash.com/photo-1565299715199-866c917206bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=960&q=80',
    desc: `Yuccie fam chicharrones keffiyeh readymade dreamcatcher plaid pinterest. Food truck thundercats brooklyn hell of. Schlitz sustainable copper mug subway tile, church-key woke ennui tilde plaid try-hard pickled art party fingerstache you probably haven't heard of them venmo. Jianbing neutra next level narwhal iPhone hoodie actually lumbersexual ennui synth tumblr cronut taxidermy. Food truck cred twee celiac shabby chic before they sold out whatever hammock, air thundercats.`,
  },
  {
    id: 3,
    title: 'Steak & Egss with herbs',
    category: 'Lunch',
    price: 6.99,
    img: 'https://images.unsplash.com/photo-1555821768-54cd53df8983?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1714&q=80',
    desc: `Fingerstache fixie wolf health goth salvia, asymmetrical af chia locavore XOXO hell of succulents kitsch quinoa meditation. Art party locavore hell of vice. Drinking vinegar austin lo-fi, raw denim jean shorts swag sartorial try-hard marfa. Sartorial pour-over enamel pin VHS 8-bit deep v helvetica schlitz chia, post-ironic migas hammock cold-pressed squid. Kale chips twee hot chicken, normcore cardigan unicorn semiotics actually. Blue bottle actually everyday carry.`,
  },
  {
    id: 4,
    title: 'Creamy Steak Fettuccine ',
    category: 'Apperitif',
    price: 20.99,
    img: 'https://images.unsplash.com/photo-1611171711791-b34fa42e9fc2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
    desc: `Shaman letterpress pitchfork photo booth. 3 wolf moon dreamcatcher enamel pin humblebrag schlitz, health goth paleo. Hashtag prism before they sold out art party cold-pressed chillwave raw denim edison bulb tilde stumptown mumblecore. Normcore art party four dollar toast dreamcatcher you probably haven't heard of them before they sold out vinyl scenester raw denim. `,
  },
  {
    id: 5,
    title: 'Air Fryer Steak',
    category: 'Main Course',
    price: 22.99,
    img: 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
    desc: `Single-origin coffee portland prism selvage. Roof party vaporware raw denim williamsburg, banh mi cloud bread knausgaard banjo bespoke. Narwhal offal brooklyn VHS pitchfork pork belly four loko actually taiyaki brunch ethical farm-to-table chia. Tattooed blue bottle umami post-ironic celiac seitan kombucha taxidermy. Copper mug unicorn pok pok austin mumblecore occupy.`,
  },
  {
    id: 6,
    title: 'Flank Steak with Chimichurri ',
    category: 'Main Course',
    price: 18.99,
    img: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80',
    desc: `Flannel sartorial health goth biodiesel tofu retro skateboard yuccie selfies williamsburg XOXO salvia occupy man bun fanny pack. Migas tote bag live-edge marfa knausgaard semiotics +1 listicle kombucha kickstarter quinoa pork belly echo park cronut vinyl. Flannel lomo palo santo, yr brunch wolf chartreuse banjo. Taxidermy keytar gentrify, cloud bread heirloom single-origin coffee raw denim. Cornhole banh mi edison bulb selvage typewriter shabby chic fashion axe.`,
  },
  {
    id: 7,
    title: 'Reverse Sear Steak ',
    category: 'Main Course',
    price: 8.99,
    img: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE4fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    desc: `Yuccie butcher salvia ethical stumptown, flannel jianbing sriracha. Occupy af you probably haven't heard of them tacos stumptown. Jianbing tofu venmo you probably haven't heard of them ethical bitters, flannel ugh wolf polaroid pug cold-pressed viral street art portland. Cray flannel keytar sriracha. Chia neutra mustache 8-bit, typewriter freegan shabby chic brooklyn. Neutra narwhal coloring book vape taxidermy umami. Knausgaard edison bulb try-hard fixie ramps venmo.`,
  },
  {
    id: 8,
    title: 'Swiss Steak Soup',
    category: 'Apperitif',
    price: 12.99,
    img: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
    desc: `Everyday carry twee literally retro, pinterest try-hard jean shorts tofu asymmetrical shaman tilde freegan. Slow-carb shoreditch vegan readymade prism celiac chicharrones keffiyeh meh twee godard locavore organic. Green juice blue bottle austin brunch banh mi wayfarers. Wolf forage retro, banjo selvage artisan truffaut. Four dollar toast put a bird on it whatever fam succulents.`,
  },
  {
    id: 9,
    title: 'Hot Garlic Steak Soup',
    category: 'Apperitif',
    price: 16.99,
    img: 'https://images.unsplash.com/photo-1568096889942-6eedde686635?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
    desc: `Pitchfork cronut synth hot chicken. Air plant chicharrones narwhal tilde, iPhone flannel asymmetrical tattooed you probably haven't heard of them small batch raw denim jean shorts. Humblebrag selvage taxidermy chillwave +1. Before they sold out intelligentsia truffaut cloud bread leggings twee actually biodiesel selvage shaman four loko poutine 90's trust fund. Dreamcatcher raw denim fashion axe chia bespoke. Meditation yuccie shaman banjo fam subway tile tumblr.`,
  },
];
export default menu;